-- SQL INSERT FOR 300 WISHES
DELETE FROM public.daily_wishes;

INSERT INTO public.daily_wishes (content, type) VALUES
('Chúc em ngày mới tràn ngập niềm vui và luôn nghĩ về anh nhé! ❤️', 'daily'),
('Hôm nay là một ngày tuyệt vời để chúng ta yêu thương nhau nhiều hơn. 🥰', 'daily'),
('Mỗi ngày thức dậy có em trong đời là điều may mắn nhất của anh. 💕', 'daily'),
('Nụ cười của em chính là năng lượng cho cả ngày dài của anh đó! ☀️', 'daily'),
('Chúc nửa kia có một ngày làm việc và học tập thật hiệu quả nhé, thương em! 😘', 'daily'),
('Anh muốn gửi ngàn nụ hôn ngọt ngào nhất đến cô gái của anh hôm nay. 💋', 'daily'),
('Dù ngày hôm nay có bận rộn thế nào, cũng đừng quên có một người luôn nhớ em. 🤗', 'daily'),
('Em là điều ngọt ngào nhất mà cuộc sống đã ban tặng cho anh. 🍭', 'daily'),
('Chúc em một ngày tràn đầy năng lượng tích cực và may mắn nha! 🍀', 'daily'),
('Hôm nay anh lại yêu em nhiều hơn hôm qua một chút rồi! 💖', 'daily'),
('Hôm nay hãy ôm người ấy thật chặt trước khi chia tay nhau ra về nhé! 🥰', 'daily'),
('Đừng quên nhắn tin bảo người ấy là bạn nhớ người ấy lắm rồi nha! 💕', 'daily'),
('Thử mua tặng người ấy một ly trà sữa loại ít đường đúng gu xem sao! 🥤', 'daily'),
('Hãy cùng người ấy ôn lại một kỷ niệm ngày đầu mới yêu nhau nhé! 🌸', 'daily'),
('Nhắc nhở nhẹ nhàng: Hãy luôn yêu thương và quan tâm đến cảm xúc của nhau hôm nay nha! ❤️', 'daily'),
('Một lời khen ngọt ngào vào buổi sáng sẽ làm cả ngày của người ấy bừng sáng đó! ☀️', 'daily'),
('Hãy dành 5 phút để gọi điện nghe giọng nói ấm áp của nửa kia hôm nay nhé! 📞', 'daily'),
('Hãy nấu một món ăn đơn giản mà người ấy yêu thích để hâm nóng tình cảm nha! 🍳', 'daily'),
('Đừng quên gửi một tấm hình tự sướng dễ thương kèm lời chúc ngày mới tốt lành! 📸', 'daily'),
('Hôm nay hãy quan tâm đến những điều nhỏ nhặt nhất của người ấy nhé! 🤗', 'daily'),
('Hôm nay là ngày tuyệt vời để ôm nhẹ từ phía sau để bày tỏ sự trân trọng 💕', 'daily'),
('Thử dành cho đối phương những cử chỉ ngọt ngào như hỏi xem hôm nay người ấy có chuyện gì vui không nhé người thương 💕', 'daily'),
('Hôm nay là ngày tuyệt vời để gửi một bài hát ngọt ngào mà bạn vô tình nghe thấy 💫', 'daily'),
('Đừng quên dành cho nửa kia những cử chỉ ngọt ngào như nhắc uống đủ nước để luôn tràn đầy năng lượng nhé người ấy ơi 🥤', 'daily'),
('Hãy dành thời gian dành cho người ấy những cử chỉ ngọt ngào như nhường nhịn đối phương một chút nếu có bất đồng nhỏ nhé nửa kia yêu dấu 🧸', 'daily'),
('Dành một chút thời gian hôm nay để gửi một tin nhắn ngọt ngào để bắt đầu ngày mới 💫', 'daily'),
('Hôm nay bạn hãy gửi một nhãn dán (sticker) thật đáng yêu và tinh nghịch 💖', 'daily'),
('Đừng quên dành cho tình yêu của bạn những cử chỉ ngọt ngào như chia sẻ một bức ảnh cũ chụp chung của hai đứa nhé 🥳', 'daily'),
('Hãy dành cho người ấy những cử chỉ ngọt ngào như gửi một cái ôm thật ấm áp qua tin nhắn để ngày hôm nay thêm ngọt ngào 💫', 'daily'),
('Hãy dành cho nửa kia những cử chỉ ngọt ngào như tạo một bất ngờ nho nhỏ bằng cách đặt đồ ăn gửi qua nha ❤️', 'daily'),
('Hãy dành cho đối phương những cử chỉ ngọt ngào như rủ đi uống trà sữa hoặc ăn món ăn vặt yêu thích đó 🍀', 'daily'),
('Hãy dành cho tình yêu của bạn những cử chỉ ngọt ngào như dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc nha người ấy ơi 🍀', 'daily'),
('Thử dành cho tình yêu của bạn những cử chỉ ngọt ngào như cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé để ngày hôm nay thêm ngọt ngào 🍀', 'daily'),
('Hãy dành thời gian dành cho tình yêu của bạn những cử chỉ ngọt ngào như hỏi xem hôm nay người ấy có chuyện gì vui không nhé tình yêu 🌷', 'daily'),
('Hãy luôn dành cho tình yêu của bạn những cử chỉ ngọt ngào như gửi một nhãn dán (sticker) thật đáng yêu và tinh nghịch nha người thương 🌷', 'daily'),
('Hãy chủ động gửi một nhãn dán (sticker) thật đáng yêu và tinh nghịch 🌸', 'daily'),
('Hãy dành cho nửa kia những cử chỉ ngọt ngào như dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc nha tình yêu 🧸', 'daily'),
('Hôm nay bạn hãy chia sẻ một bức ảnh cũ chụp chung của hai đứa nhé 🥤', 'daily'),
('Hôm nay hãy gửi một cái ôm thật ấm áp qua tin nhắn 🍀', 'daily'),
('Hôm nay bạn hãy nắm tay thật chặt khi cùng nhau đi bộ dưới phố 🥤', 'daily'),
('Dành một chút thời gian hôm nay để gửi một bài hát ngọt ngào mà bạn vô tình nghe thấy 🥤', 'daily'),
('Đừng quên dành cho đối phương những cử chỉ ngọt ngào như dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc nhé 💖', 'daily'),
('Hôm nay là ngày tuyệt vời để ôm nhẹ từ phía sau để bày tỏ sự trân trọng ✨', 'daily'),
('Hôm nay là ngày tuyệt vời để hỏi xem có cần bạn giúp đỡ việc gì không nhé 💫', 'daily'),
('Dành một chút thời gian hôm nay để hôn nhẹ lên trán để thể hiện sự chở che yêu thương ✨', 'daily'),
('Hôm nay là ngày tuyệt vời để chia sẻ một câu chuyện vui vẻ bạn gặp hôm nay ☀️', 'daily'),
('Hãy luôn dành cho nửa kia những cử chỉ ngọt ngào như nhắc nhở đi ngủ sớm để giữ gìn nhan sắc và sức khỏe nhé để ngày hôm nay thêm ngọt ngào 🌷', 'daily'),
('Đừng quên dành cho đối phương những cử chỉ ngọt ngào như gửi một bài hát ngọt ngào mà bạn vô tình nghe thấy nha 💖', 'daily'),
('Hôm nay bạn hãy gửi một nhãn dán (sticker) thật đáng yêu và tinh nghịch 🍀', 'daily'),
('Hôm nay là ngày tuyệt vời để viết một mẩu giấy nhớ ngọt ngào gửi kèm nhé 😘', 'daily'),
('Hôm nay là ngày tuyệt vời để lên kế hoạch cho một buổi hẹn hò lãng mạn cuối tuần này 🤝', 'daily'),
('Hãy luôn dành cho đối phương những cử chỉ ngọt ngào như nhắc nhở đi ngủ sớm để giữ gìn nhan sắc và sức khỏe nhé tình yêu của anh/em 🤝', 'daily'),
('Hãy luôn dành cho đối phương những cử chỉ ngọt ngào như hỏi xem có cần bạn giúp đỡ việc gì không nhé để tình cảm thêm bền chặt 😍', 'daily'),
('Hôm nay bạn hãy kiên nhẫn lắng nghe những tâm sự nhỏ to sau ngày làm việc 🥤', 'daily'),
('Hôm nay bạn hãy lên kế hoạch cho một buổi hẹn hò lãng mạn cuối tuần này 🍀', 'daily'),
('Thử dành cho người ấy những cử chỉ ngọt ngào như nhường nhịn đối phương một chút nếu có bất đồng nhỏ nhé để ngày hôm nay thêm ngọt ngào 💋', 'daily'),
('Hãy dành thời gian dành cho người thương những cử chỉ ngọt ngào như ôm nhẹ từ phía sau để bày tỏ sự trân trọng nha tình yêu 💕', 'daily'),
('Dành một chút thời gian hôm nay để hỏi xem có cần bạn giúp đỡ việc gì không nhé 😘', 'daily'),
('Hãy dành cho người thương những cử chỉ ngọt ngào như gửi một nhãn dán (sticker) thật đáng yêu và tinh nghịch nha 🍀', 'daily'),
('Hôm nay là ngày tuyệt vời để rủ đi uống trà sữa hoặc ăn món ăn vặt yêu thích 🤗', 'daily'),
('Hãy dành cho người thương những cử chỉ ngọt ngào như viết một mẩu giấy nhớ ngọt ngào gửi kèm nhé 🤗', 'daily'),
('Hãy dành cho tình yêu của bạn những cử chỉ ngọt ngào như gửi một cái ôm thật ấm áp qua tin nhắn nhé tình yêu của anh/em 🤝', 'daily'),
('Hãy dành thời gian dành cho người ấy những cử chỉ ngọt ngào như chia sẻ một bức ảnh cũ chụp chung của hai đứa nhé nửa kia yêu dấu 🍀', 'daily'),
('Thử dành cho đối phương những cử chỉ ngọt ngào như hỏi xem có cần bạn giúp đỡ việc gì không nhé đó ☀️', 'daily'),
('Thử dành cho đối phương những cử chỉ ngọt ngào như rủ đi uống trà sữa hoặc ăn món ăn vặt yêu thích nha 🥤', 'daily'),
('Hãy dành cho tình yêu của bạn những cử chỉ ngọt ngào như hỏi xem có cần bạn giúp đỡ việc gì không nhé để ngày hôm nay thêm ngọt ngào 🌸', 'daily'),
('Hãy dành cho người ấy những cử chỉ ngọt ngào như chia sẻ một bức ảnh cũ chụp chung của hai đứa nhé 🥤', 'daily'),
('Dành một chút thời gian hôm nay để lên kế hoạch cho một buổi hẹn hò lãng mạn cuối tuần này ✨', 'daily'),
('Dành một chút thời gian hôm nay để nhắc uống đủ nước để luôn tràn đầy năng lượng nhé 😍', 'daily'),
('Hôm nay bạn hãy gọi điện thoại chỉ để nghe giọng nói quen thuộc 🤝', 'daily'),
('Hãy dành cho nửa kia những cử chỉ ngọt ngào như chia sẻ một bức ảnh cũ chụp chung của hai đứa nhé người thương 😍', 'daily'),
('Dành một chút thời gian hôm nay để dành cho nhau 10 phút nói chuyện hoàn toàn không bấm điện thoại 🍿', 'daily'),
('Hãy dành thời gian dành cho nửa kia những cử chỉ ngọt ngào như gửi một bài hát ngọt ngào mà bạn vô tình nghe thấy nhé nửa kia yêu dấu 🎁', 'daily'),
('Hãy dành cho đối phương những cử chỉ ngọt ngào như hỏi xem có cần bạn giúp đỡ việc gì không nhé đó 💖', 'daily'),
('Hãy dành thời gian dành cho đối phương những cử chỉ ngọt ngào như tạo một bất ngờ nho nhỏ bằng cách đặt đồ ăn gửi qua nha tình yêu 🍿', 'daily'),
('Thử dành cho tình yêu của bạn những cử chỉ ngọt ngào như hôn nhẹ lên trán để thể hiện sự chở che yêu thương nhé nửa kia yêu dấu 🌸', 'daily'),
('Hãy chủ động nhắc nhở đi ngủ sớm để giữ gìn nhan sắc và sức khỏe nhé 💖', 'daily'),
('Hôm nay là ngày tuyệt vời để nhắn tin hỏi thăm xem có mệt không nhé 🎁', 'daily'),
('Hôm nay là ngày tuyệt vời để viết một mẩu giấy nhớ ngọt ngào gửi kèm nhé 🥤', 'daily'),
('Hôm nay bạn hãy dành cho nhau 10 phút nói chuyện hoàn toàn không bấm điện thoại ❤️', 'daily'),
('Hôm nay bạn hãy nhường nhịn đối phương một chút nếu có bất đồng nhỏ nhé 💫', 'daily'),
('Thử dành cho người thương những cử chỉ ngọt ngào như dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc nhé nửa kia yêu dấu 💋', 'daily'),
('Hôm nay hãy lên kế hoạch cho một buổi hẹn hò lãng mạn cuối tuần này 🥰', 'daily'),
('Dành một chút thời gian hôm nay để gửi một nhãn dán (sticker) thật đáng yêu và tinh nghịch 🧸', 'daily'),
('Đừng quên dành cho tình yêu của bạn những cử chỉ ngọt ngào như chia sẻ một câu chuyện vui vẻ bạn gặp hôm nay nhé 🥰', 'daily'),
('Đừng quên dành cho đối phương những cử chỉ ngọt ngào như chia sẻ một câu chuyện vui vẻ bạn gặp hôm nay nhé ❤️', 'daily'),
('Đừng quên dành cho người thương những cử chỉ ngọt ngào như nhắc uống đủ nước để luôn tràn đầy năng lượng nhé để tình cảm thêm bền chặt 🎁', 'daily'),
('Hôm nay bạn hãy chuẩn bị một viên kẹo ngọt hoặc món quà nhỏ bỏ vào túi áo nhé ✨', 'daily'),
('Hãy luôn dành cho tình yêu của bạn những cử chỉ ngọt ngào như gửi một bài hát ngọt ngào mà bạn vô tình nghe thấy nha ✨', 'daily'),
('Hãy dành cho tình yêu của bạn những cử chỉ ngọt ngào như chia sẻ một bức ảnh cũ chụp chung của hai đứa nhé tình yêu 🤝', 'daily'),
('Đừng quên dành cho tình yêu của bạn những cử chỉ ngọt ngào như gửi một tin nhắn ngọt ngào để bắt đầu ngày mới nhé tình yêu của anh/em ✨', 'daily'),
('Hãy chủ động khen ngợi phong cách ăn mặc hoặc mùi nước hoa hôm nay 🥰', 'daily'),
('Dành một chút thời gian hôm nay để động viên và cổ vũ cho những nỗ lực hôm nay của người ấy nhé 💕', 'daily'),
('Hãy dành thời gian dành cho người ấy những cử chỉ ngọt ngào như nhắc uống đủ nước để luôn tràn đầy năng lượng nhé để tình cảm thêm bền chặt 💕', 'daily'),
('Hôm nay bạn hãy nói lời yêu thương ngọt ngào trước khi đi ngủ nhé 🌷', 'daily'),
('Hãy luôn dành cho nửa kia những cử chỉ ngọt ngào như hỏi xem hôm nay người ấy có chuyện gì vui không nhé ✨', 'daily'),
('Hôm nay hãy gửi một cái ôm thật ấm áp qua tin nhắn 😍', 'daily'),
('Hãy luôn dành cho đối phương những cử chỉ ngọt ngào như nhắc uống đủ nước để luôn tràn đầy năng lượng nhé 😘', 'daily'),
('Thử dành cho người thương những cử chỉ ngọt ngào như cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé để ngày hôm nay thêm ngọt ngào 🍀', 'daily'),
('Hãy dành cho nửa kia những cử chỉ ngọt ngào như nói lời yêu thương ngọt ngào trước khi đi ngủ nhé để tình cảm thêm bền chặt 🎁', 'daily'),
('Hãy luôn dành cho tình yêu của bạn những cử chỉ ngọt ngào như dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc để tình cảm thêm bền chặt ✨', 'daily'),
('Hãy dành thời gian dành cho người thương những cử chỉ ngọt ngào như viết một mẩu giấy nhớ ngọt ngào gửi kèm nhé ✨', 'daily'),
('Hôm nay bạn hãy dành cho nhau 10 phút nói chuyện hoàn toàn không bấm điện thoại 💕', 'daily'),
('Hãy dành thời gian dành cho đối phương những cử chỉ ngọt ngào như ôm nhẹ từ phía sau để bày tỏ sự trân trọng đó 🌷', 'daily'),
('Hôm nay là ngày tuyệt vời để tạo một bất ngờ nho nhỏ bằng cách đặt đồ ăn gửi qua 🤝', 'daily'),
('Hãy chủ động khen ngợi phong cách ăn mặc hoặc mùi nước hoa hôm nay 🌸', 'daily'),
('Đừng quên dành cho người thương những cử chỉ ngọt ngào như gọi điện thoại chỉ để nghe giọng nói quen thuộc nhé nửa kia yêu dấu 🎁', 'daily'),
('Hôm nay bạn hãy rủ đi uống trà sữa hoặc ăn món ăn vặt yêu thích 🥰', 'daily'),
('Hôm nay bạn hãy cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé 🍿', 'daily'),
('Hãy luôn dành cho nửa kia những cử chỉ ngọt ngào như gửi một nhãn dán (sticker) thật đáng yêu và tinh nghịch nha người ấy ơi 🤗', 'daily'),
('Dành một chút thời gian hôm nay để nói lời yêu thương ngọt ngào trước khi đi ngủ nhé 🥤', 'daily'),
('Hôm nay là ngày tuyệt vời để rủ đi uống trà sữa hoặc ăn món ăn vặt yêu thích 🎁', 'daily'),
('Hôm nay là ngày tuyệt vời để động viên và cổ vũ cho những nỗ lực hôm nay của người ấy nhé 💫', 'daily'),
('Dành một chút thời gian hôm nay để khen ngợi phong cách ăn mặc hoặc mùi nước hoa hôm nay 🥤', 'daily'),
('Hãy dành cho nửa kia những cử chỉ ngọt ngào như gửi một tin nhắn ngọt ngào để bắt đầu ngày mới để tình cảm thêm bền chặt 🥰', 'daily'),
('Thử dành cho tình yêu của bạn những cử chỉ ngọt ngào như nhắc uống đủ nước để luôn tràn đầy năng lượng nhé để tình cảm thêm bền chặt 🥰', 'daily'),
('Hãy luôn dành cho đối phương những cử chỉ ngọt ngào như gửi một bài hát ngọt ngào mà bạn vô tình nghe thấy nha 🧸', 'daily'),
('Hãy luôn dành cho người thương những cử chỉ ngọt ngào như động viên và cổ vũ cho những nỗ lực hôm nay của người ấy nhé người ấy ơi 🍿', 'daily'),
('Hôm nay là ngày tuyệt vời để dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc 🌷', 'daily'),
('Hãy dành cho người thương những cử chỉ ngọt ngào như nhắc nhở ăn uống đúng giờ và giữ gìn sức khỏe nhé 💖', 'daily'),
('Hãy luôn dành cho nửa kia những cử chỉ ngọt ngào như kiên nhẫn lắng nghe những tâm sự nhỏ to sau ngày làm việc để ngày hôm nay thêm ngọt ngào 🍀', 'daily'),
('Hôm nay hãy hỏi xem có cần bạn giúp đỡ việc gì không nhé ❤️', 'daily'),
('Hãy luôn dành cho đối phương những cử chỉ ngọt ngào như hôn nhẹ lên trán để thể hiện sự chở che yêu thương nha người thương 🤝', 'daily'),
('Dành một chút thời gian hôm nay để lên kế hoạch cho một buổi hẹn hò lãng mạn cuối tuần này 🧸', 'daily'),
('Hôm nay hãy chia sẻ một câu chuyện vui vẻ bạn gặp hôm nay 🥳', 'daily'),
('Hãy dành thời gian dành cho tình yêu của bạn những cử chỉ ngọt ngào như gửi một cái ôm thật ấm áp qua tin nhắn để ngày hôm nay thêm ngọt ngào 🌷', 'daily'),
('Hãy chủ động hôn nhẹ lên trán để thể hiện sự chở che yêu thương 🤝', 'daily'),
('Hãy chủ động nhắc nhở đi ngủ sớm để giữ gìn nhan sắc và sức khỏe nhé 😘', 'daily'),
('Thử dành cho đối phương những cử chỉ ngọt ngào như gửi một nhãn dán (sticker) thật đáng yêu và tinh nghịch nhé tình yêu của anh/em ❤️', 'daily'),
('Thử dành cho nửa kia những cử chỉ ngọt ngào như gửi một bài hát ngọt ngào mà bạn vô tình nghe thấy để tình cảm thêm bền chặt 🍿', 'daily'),
('Hãy luôn dành cho nửa kia những cử chỉ ngọt ngào như gửi một bài hát ngọt ngào mà bạn vô tình nghe thấy nhé ☀️', 'daily'),
('Hãy dành cho nửa kia những cử chỉ ngọt ngào như chia sẻ một bức ảnh cũ chụp chung của hai đứa nhé 🍀', 'daily'),
('Hãy dành thời gian dành cho người thương những cử chỉ ngọt ngào như ôm nhẹ từ phía sau để bày tỏ sự trân trọng nha người thương ☀️', 'daily'),
('Hãy chủ động kiên nhẫn lắng nghe những tâm sự nhỏ to sau ngày làm việc 💫', 'daily'),
('Hôm nay hãy nhắc nhở đi ngủ sớm để giữ gìn nhan sắc và sức khỏe nhé 🌷', 'daily'),
('Hãy dành thời gian dành cho nửa kia những cử chỉ ngọt ngào như nhắc uống đủ nước để luôn tràn đầy năng lượng nhé tình yêu của anh/em 🤗', 'daily'),
('Hãy luôn dành cho người ấy những cử chỉ ngọt ngào như kiên nhẫn lắng nghe những tâm sự nhỏ to sau ngày làm việc để tình cảm thêm bền chặt 💕', 'daily'),
('Thử dành cho tình yêu của bạn những cử chỉ ngọt ngào như hôn nhẹ lên trán để thể hiện sự chở che yêu thương để ngày hôm nay thêm ngọt ngào 💕', 'daily'),
('Hãy dành thời gian dành cho người ấy những cử chỉ ngọt ngào như nhắc nhở ăn uống đúng giờ và giữ gìn sức khỏe nhé tình yêu 🌷', 'daily'),
('Hãy chủ động hỏi xem có cần bạn giúp đỡ việc gì không nhé ☀️', 'daily'),
('Thử dành cho nửa kia những cử chỉ ngọt ngào như nhường nhịn đối phương một chút nếu có bất đồng nhỏ nhé ❤️', 'daily'),
('Hãy dành cho tình yêu của bạn những cử chỉ ngọt ngào như gửi một lời chúc ngủ ngon thật ấm áp và dễ thương nha người ấy ơi 💕', 'daily'),
('Hãy dành cho tình yêu của bạn những cử chỉ ngọt ngào như ôm nhẹ từ phía sau để bày tỏ sự trân trọng để tình cảm thêm bền chặt 🥤', 'daily'),
('Thử dành cho nửa kia những cử chỉ ngọt ngào như nhường nhịn đối phương một chút nếu có bất đồng nhỏ nhé người ấy ơi 😍', 'daily'),
('Hôm nay hãy dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc ☀️', 'daily'),
('Thử dành cho người thương những cử chỉ ngọt ngào như nhắc nhở ăn uống đúng giờ và giữ gìn sức khỏe nhé 🍿', 'daily'),
('Đừng quên dành cho người ấy những cử chỉ ngọt ngào như nhắn tin hỏi thăm xem có mệt không nhé đó 🥰', 'daily'),
('Dành một chút thời gian hôm nay để nhắc nhở ăn uống đúng giờ và giữ gìn sức khỏe nhé ❤️', 'daily'),
('Hãy dành thời gian dành cho nửa kia những cử chỉ ngọt ngào như nhắc uống đủ nước để luôn tràn đầy năng lượng nhé người ấy ơi 🧸', 'daily'),
('Hôm nay là ngày tuyệt vời để gọi điện thoại chỉ để nghe giọng nói quen thuộc 🤗', 'daily'),
('Hãy luôn dành cho nửa kia những cử chỉ ngọt ngào như gọi điện thoại chỉ để nghe giọng nói quen thuộc nha người ấy ơi 💋', 'daily'),
('Hãy luôn dành cho đối phương những cử chỉ ngọt ngào như gửi một nhãn dán (sticker) thật đáng yêu và tinh nghịch nhé tình yêu của anh/em 🎁', 'daily'),
('Thử dành cho tình yêu của bạn những cử chỉ ngọt ngào như dành cho nhau 10 phút nói chuyện hoàn toàn không bấm điện thoại để ngày hôm nay thêm ngọt ngào ☀️', 'daily'),
('Dành một chút thời gian hôm nay để nhắc nhở ăn uống đúng giờ và giữ gìn sức khỏe nhé 🍀', 'daily'),
('Hôm nay bạn hãy gọi điện thoại chỉ để nghe giọng nói quen thuộc 🍿', 'daily'),
('Thử dành cho đối phương những cử chỉ ngọt ngào như chia sẻ một câu chuyện vui vẻ bạn gặp hôm nay nhé nửa kia yêu dấu ☀️', 'daily'),
('Hôm nay hãy nhắc uống đủ nước để luôn tràn đầy năng lượng nhé 🥰', 'daily'),
('Thử dành cho người thương những cử chỉ ngọt ngào như tạo một bất ngờ nho nhỏ bằng cách đặt đồ ăn gửi qua nha người thương 🥰', 'daily'),
('Hôm nay bạn hãy lên kế hoạch cho một buổi hẹn hò lãng mạn cuối tuần này 🌷', 'daily'),
('Hôm nay bạn hãy nhắc uống đủ nước để luôn tràn đầy năng lượng nhé 🧸', 'daily'),
('Hãy dành thời gian dành cho đối phương những cử chỉ ngọt ngào như chia sẻ một câu chuyện vui vẻ bạn gặp hôm nay nha người thương 🧸', 'daily'),
('Đừng quên dành cho đối phương những cử chỉ ngọt ngào như gọi điện thoại chỉ để nghe giọng nói quen thuộc nha người thương 🤗', 'daily'),
('Hôm nay hãy gửi một tin nhắn ngọt ngào để bắt đầu ngày mới 💋', 'daily'),
('Dành một chút thời gian hôm nay để gửi một tin nhắn ngọt ngào để bắt đầu ngày mới 🥤', 'daily'),
('Hôm nay bạn hãy dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc 🎁', 'daily'),
('Hôm nay là ngày tuyệt vời để lên kế hoạch cho một buổi hẹn hò lãng mạn cuối tuần này 🤗', 'daily'),
('Hãy luôn dành cho người ấy những cử chỉ ngọt ngào như rủ đi uống trà sữa hoặc ăn món ăn vặt yêu thích nhé nửa kia yêu dấu ❤️', 'daily'),
('Hãy dành cho người thương những cử chỉ ngọt ngào như nhắn tin hỏi thăm xem có mệt không nhé để tình cảm thêm bền chặt ☀️', 'daily'),
('Hãy dành thời gian dành cho tình yêu của bạn những cử chỉ ngọt ngào như dành cho nhau 10 phút nói chuyện hoàn toàn không bấm điện thoại nhé nửa kia yêu dấu 🍿', 'daily'),
('Hôm nay bạn hãy dành cho nhau 10 phút nói chuyện hoàn toàn không bấm điện thoại 💫', 'daily'),
('Hãy chủ động chia sẻ một bức ảnh cũ chụp chung của hai đứa nhé 💋', 'daily'),
('Đừng quên dành cho người ấy những cử chỉ ngọt ngào như chia sẻ một câu chuyện vui vẻ bạn gặp hôm nay nhé 😘', 'daily'),
('Hôm nay là ngày tuyệt vời để tạo một bất ngờ nho nhỏ bằng cách đặt đồ ăn gửi qua 🌷', 'daily'),
('Đừng quên dành cho người ấy những cử chỉ ngọt ngào như cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé người thương 🥰', 'daily'),
('Hãy chủ động gửi một tin nhắn ngọt ngào để bắt đầu ngày mới ☀️', 'daily'),
('Hôm nay là ngày tuyệt vời để viết một mẩu giấy nhớ ngọt ngào gửi kèm nhé 🍿', 'daily'),
('Hôm nay bạn hãy cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé ❤️', 'daily'),
('Hôm nay bạn hãy lên kế hoạch cho một buổi hẹn hò lãng mạn cuối tuần này 💕', 'daily'),
('Thử dành cho đối phương những cử chỉ ngọt ngào như kiên nhẫn lắng nghe những tâm sự nhỏ to sau ngày làm việc nhé tình yêu của anh/em 🍀', 'daily'),
('Hãy dành cho tình yêu của bạn những cử chỉ ngọt ngào như tạo một bất ngờ nho nhỏ bằng cách đặt đồ ăn gửi qua nha ☀️', 'daily'),
('Hôm nay là ngày tuyệt vời để nhắc nhở ăn uống đúng giờ và giữ gìn sức khỏe nhé 💖', 'daily'),
('Hôm nay hãy cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé 🎁', 'daily'),
('Hôm nay là ngày tuyệt vời để rủ đi uống trà sữa hoặc ăn món ăn vặt yêu thích 💫', 'daily'),
('Hôm nay bạn hãy nhường nhịn đối phương một chút nếu có bất đồng nhỏ nhé 🍿', 'daily'),
('Hôm nay hãy chuẩn bị một viên kẹo ngọt hoặc món quà nhỏ bỏ vào túi áo nhé ✨', 'daily'),
('Hôm nay là ngày tuyệt vời để gửi một nhãn dán (sticker) thật đáng yêu và tinh nghịch 💫', 'daily'),
('Hãy luôn dành cho người ấy những cử chỉ ngọt ngào như chia sẻ một câu chuyện vui vẻ bạn gặp hôm nay đó 🍿', 'daily'),
('Hãy chủ động nhắc nhở ăn uống đúng giờ và giữ gìn sức khỏe nhé 🧸', 'daily'),
('Hãy dành thời gian dành cho nửa kia những cử chỉ ngọt ngào như tạo một bất ngờ nho nhỏ bằng cách đặt đồ ăn gửi qua để ngày hôm nay thêm ngọt ngào 😘', 'daily'),
('Hãy luôn dành cho đối phương những cử chỉ ngọt ngào như nhắc uống đủ nước để luôn tràn đầy năng lượng nhé người thương 💋', 'daily'),
('Đừng quên dành cho người ấy những cử chỉ ngọt ngào như ôm nhẹ từ phía sau để bày tỏ sự trân trọng nhé 🌸', 'daily'),
('Hôm nay bạn hãy hỏi xem hôm nay người ấy có chuyện gì vui không nhé ❤️', 'daily'),
('Hãy luôn dành cho tình yêu của bạn những cử chỉ ngọt ngào như dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc nha người ấy ơi 🥰', 'daily'),
('Thử dành cho nửa kia những cử chỉ ngọt ngào như nhắc nhở ăn uống đúng giờ và giữ gìn sức khỏe nhé để ngày hôm nay thêm ngọt ngào 🥳', 'daily'),
('Hãy chủ động nhường nhịn đối phương một chút nếu có bất đồng nhỏ nhé 💋', 'daily'),
('Hãy luôn dành cho tình yêu của bạn những cử chỉ ngọt ngào như nhắn tin hỏi thăm xem có mệt không nhé để ngày hôm nay thêm ngọt ngào ✨', 'daily'),
('Hãy luôn dành cho người ấy những cử chỉ ngọt ngào như cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé nửa kia yêu dấu 💫', 'daily'),
('Hôm nay bạn hãy khen ngợi phong cách ăn mặc hoặc mùi nước hoa hôm nay 🥰', 'daily'),
('Dành một chút thời gian hôm nay để nắm tay thật chặt khi cùng nhau đi bộ dưới phố 🧸', 'daily'),
('Hãy chủ động lên kế hoạch cho một buổi hẹn hò lãng mạn cuối tuần này 🍿', 'daily'),
('Đừng quên dành cho đối phương những cử chỉ ngọt ngào như gửi một lời chúc ngủ ngon thật ấm áp và dễ thương nhé nửa kia yêu dấu 💕', 'daily'),
('Thử dành cho nửa kia những cử chỉ ngọt ngào như tạo một bất ngờ nho nhỏ bằng cách đặt đồ ăn gửi qua nha tình yêu 💫', 'daily'),
('Hãy dành thời gian dành cho người thương những cử chỉ ngọt ngào như hỏi xem hôm nay người ấy có chuyện gì vui không nhé người thương 🍿', 'daily'),
('Hãy chủ động gửi một bài hát ngọt ngào mà bạn vô tình nghe thấy 💫', 'daily'),
('Đừng quên dành cho tình yêu của bạn những cử chỉ ngọt ngào như dành cho nhau 10 phút nói chuyện hoàn toàn không bấm điện thoại nha người ấy ơi ✨', 'daily'),
('Hãy dành thời gian dành cho nửa kia những cử chỉ ngọt ngào như hỏi xem có cần bạn giúp đỡ việc gì không nhé đó 🎁', 'daily'),
('Đừng quên dành cho tình yêu của bạn những cử chỉ ngọt ngào như hỏi xem hôm nay người ấy có chuyện gì vui không nhé để tình cảm thêm bền chặt 💖', 'daily'),
('Hãy chủ động chia sẻ một bức ảnh cũ chụp chung của hai đứa nhé 🧸', 'daily'),
('Hôm nay là ngày tuyệt vời để khen ngợi phong cách ăn mặc hoặc mùi nước hoa hôm nay 😘', 'daily'),
('Dành một chút thời gian hôm nay để nhắc uống đủ nước để luôn tràn đầy năng lượng nhé 🍀', 'daily'),
('Hãy dành cho người thương những cử chỉ ngọt ngào như chuẩn bị một viên kẹo ngọt hoặc món quà nhỏ bỏ vào túi áo nhé để ngày hôm nay thêm ngọt ngào 💕', 'daily'),
('Hôm nay bạn hãy động viên và cổ vũ cho những nỗ lực hôm nay của người ấy nhé ✨', 'daily'),
('Dành một chút thời gian hôm nay để kiên nhẫn lắng nghe những tâm sự nhỏ to sau ngày làm việc 🍀', 'daily'),
('Đừng quên dành cho người ấy những cử chỉ ngọt ngào như tạo một bất ngờ nho nhỏ bằng cách đặt đồ ăn gửi qua nha 💖', 'daily'),
('Hôm nay là ngày tuyệt vời để dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc 🤝', 'daily'),
('Hãy luôn dành cho đối phương những cử chỉ ngọt ngào như gửi một nhãn dán (sticker) thật đáng yêu và tinh nghịch để tình cảm thêm bền chặt 🧸', 'daily'),
('Hãy dành thời gian dành cho tình yêu của bạn những cử chỉ ngọt ngào như kiên nhẫn lắng nghe những tâm sự nhỏ to sau ngày làm việc nha ❤️', 'daily'),
('Hôm nay bạn hãy cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé 💖', 'daily'),
('Hôm nay là ngày tuyệt vời để hôn nhẹ lên trán để thể hiện sự chở che yêu thương 🍀', 'daily'),
('Hãy luôn dành cho người thương những cử chỉ ngọt ngào như gửi một cái ôm thật ấm áp qua tin nhắn nhé 💖', 'daily'),
('Hôm nay hãy gọi điện thoại chỉ để nghe giọng nói quen thuộc 🥳', 'daily'),
('Hãy luôn dành cho đối phương những cử chỉ ngọt ngào như gửi một bài hát ngọt ngào mà bạn vô tình nghe thấy nha người thương 🤗', 'daily'),
('Hãy luôn dành cho người thương những cử chỉ ngọt ngào như khen ngợi phong cách ăn mặc hoặc mùi nước hoa hôm nay để tình cảm thêm bền chặt 🌷', 'daily'),
('Hôm nay hãy cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé 🥤', 'daily'),
('Hãy chủ động dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc 😍', 'daily'),
('Hôm nay bạn hãy cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé ✨', 'daily'),
('Hãy chủ động kiên nhẫn lắng nghe những tâm sự nhỏ to sau ngày làm việc 🥰', 'daily'),
('Hôm nay hãy rủ đi uống trà sữa hoặc ăn món ăn vặt yêu thích ✨', 'daily'),
('Hãy chủ động gửi một tin nhắn ngọt ngào để bắt đầu ngày mới 💕', 'daily'),
('Thử dành cho tình yêu của bạn những cử chỉ ngọt ngào như khen ngợi phong cách ăn mặc hoặc mùi nước hoa hôm nay nha tình yêu 💕', 'daily'),
('Hãy chủ động rủ đi uống trà sữa hoặc ăn món ăn vặt yêu thích 🍀', 'daily'),
('Hãy luôn dành cho người thương những cử chỉ ngọt ngào như chia sẻ một bức ảnh cũ chụp chung của hai đứa nhé tình yêu 🧸', 'daily'),
('Hôm nay là ngày tuyệt vời để gửi một tin nhắn ngọt ngào để bắt đầu ngày mới 😍', 'daily'),
('Hôm nay hãy động viên và cổ vũ cho những nỗ lực hôm nay của người ấy nhé 🥳', 'daily'),
('Hãy luôn dành cho người ấy những cử chỉ ngọt ngào như gửi một tin nhắn ngọt ngào để bắt đầu ngày mới đó ☀️', 'daily'),
('Hãy luôn dành cho đối phương những cử chỉ ngọt ngào như gửi một nhãn dán (sticker) thật đáng yêu và tinh nghịch nha tình yêu 💫', 'daily'),
('Hôm nay bạn hãy chia sẻ một câu chuyện vui vẻ bạn gặp hôm nay 🧸', 'daily'),
('Thử dành cho người thương những cử chỉ ngọt ngào như viết một mẩu giấy nhớ ngọt ngào gửi kèm nhé người ấy ơi 🤝', 'daily'),
('Đừng quên dành cho nửa kia những cử chỉ ngọt ngào như chuẩn bị một viên kẹo ngọt hoặc món quà nhỏ bỏ vào túi áo nhé để ngày hôm nay thêm ngọt ngào 😘', 'daily'),
('Hãy chủ động cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé 💕', 'daily'),
('Đừng quên dành cho người thương những cử chỉ ngọt ngào như lên kế hoạch cho một buổi hẹn hò lãng mạn cuối tuần này nhé 🥤', 'daily'),
('Hôm nay là ngày tuyệt vời để nhắn tin hỏi thăm xem có mệt không nhé 🤗', 'daily'),
('Hôm nay bạn hãy ôm nhẹ từ phía sau để bày tỏ sự trân trọng 💕', 'daily'),
('Đừng quên dành cho nửa kia những cử chỉ ngọt ngào như động viên và cổ vũ cho những nỗ lực hôm nay của người ấy nhé tình yêu của anh/em 😍', 'daily'),
('Đừng quên dành cho nửa kia những cử chỉ ngọt ngào như gửi một lời chúc ngủ ngon thật ấm áp và dễ thương nha người ấy ơi 💕', 'daily'),
('Hôm nay bạn hãy nhường nhịn đối phương một chút nếu có bất đồng nhỏ nhé 🥰', 'daily'),
('Hãy dành thời gian dành cho người ấy những cử chỉ ngọt ngào như gọi điện thoại chỉ để nghe giọng nói quen thuộc để ngày hôm nay thêm ngọt ngào 🧸', 'daily'),
('Hãy dành cho nửa kia những cử chỉ ngọt ngào như nhắc nhở đi ngủ sớm để giữ gìn nhan sắc và sức khỏe nhé tình yêu 💋', 'daily'),
('Hãy dành cho nửa kia những cử chỉ ngọt ngào như nhắn tin hỏi thăm xem có mệt không nhé để tình cảm thêm bền chặt 💫', 'daily'),
('Dành một chút thời gian hôm nay để hôn nhẹ lên trán để thể hiện sự chở che yêu thương 💖', 'daily'),
('Hãy chủ động hỏi xem có cần bạn giúp đỡ việc gì không nhé 🌸', 'daily'),
('Hôm nay hãy hỏi xem hôm nay người ấy có chuyện gì vui không nhé 😍', 'daily'),
('Hãy dành thời gian dành cho nửa kia những cử chỉ ngọt ngào như khen ngợi phong cách ăn mặc hoặc mùi nước hoa hôm nay nhé nửa kia yêu dấu 🥳', 'daily'),
('Dành một chút thời gian hôm nay để nhắn tin hỏi thăm xem có mệt không nhé 🌸', 'daily'),
('Đừng quên dành cho người ấy những cử chỉ ngọt ngào như gọi điện thoại chỉ để nghe giọng nói quen thuộc để tình cảm thêm bền chặt 💫', 'daily'),
('Hãy dành thời gian dành cho tình yêu của bạn những cử chỉ ngọt ngào như nhường nhịn đối phương một chút nếu có bất đồng nhỏ nhé người thương 🌷', 'daily'),
('Hãy chủ động nắm tay thật chặt khi cùng nhau đi bộ dưới phố ❤️', 'daily'),
('Hãy luôn dành cho tình yêu của bạn những cử chỉ ngọt ngào như nhường nhịn đối phương một chút nếu có bất đồng nhỏ nhé 😘', 'daily'),
('Thử dành cho nửa kia những cử chỉ ngọt ngào như lên kế hoạch cho một buổi hẹn hò lãng mạn cuối tuần này nhé 🥰', 'daily'),
('Dành một chút thời gian hôm nay để chuẩn bị một viên kẹo ngọt hoặc món quà nhỏ bỏ vào túi áo nhé 🍀', 'daily'),
('Hãy dành thời gian dành cho người thương những cử chỉ ngọt ngào như hỏi xem hôm nay người ấy có chuyện gì vui không nhé tình yêu 🍿', 'daily'),
('Hôm nay là ngày tuyệt vời để gửi một bài hát ngọt ngào mà bạn vô tình nghe thấy 🥳', 'daily'),
('Hôm nay hãy nhắc uống đủ nước để luôn tràn đầy năng lượng nhé 💫', 'daily'),
('Hãy dành cho tình yêu của bạn những cử chỉ ngọt ngào như chia sẻ một câu chuyện vui vẻ bạn gặp hôm nay nha người thương 🌷', 'daily'),
('Hãy luôn dành cho đối phương những cử chỉ ngọt ngào như khen ngợi phong cách ăn mặc hoặc mùi nước hoa hôm nay để ngày hôm nay thêm ngọt ngào 😘', 'daily'),
('Thử dành cho người ấy những cử chỉ ngọt ngào như dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc đó 💫', 'daily'),
('Thử dành cho người thương những cử chỉ ngọt ngào như động viên và cổ vũ cho những nỗ lực hôm nay của người ấy nhé để ngày hôm nay thêm ngọt ngào 🧸', 'daily'),
('Dành một chút thời gian hôm nay để nhường nhịn đối phương một chút nếu có bất đồng nhỏ nhé 💋', 'daily'),
('Hôm nay hãy hỏi xem hôm nay người ấy có chuyện gì vui không nhé ❤️', 'daily'),
('Hôm nay hãy hôn nhẹ lên trán để thể hiện sự chở che yêu thương 💖', 'daily'),
('Thử dành cho nửa kia những cử chỉ ngọt ngào như nắm tay thật chặt khi cùng nhau đi bộ dưới phố nhé 🍀', 'daily'),
('Hãy dành thời gian dành cho người thương những cử chỉ ngọt ngào như tạo một bất ngờ nho nhỏ bằng cách đặt đồ ăn gửi qua nha 💫', 'daily'),
('Hôm nay là ngày tuyệt vời để nhường nhịn đối phương một chút nếu có bất đồng nhỏ nhé 🤗', 'daily'),
('Thử dành cho nửa kia những cử chỉ ngọt ngào như gửi một lời chúc ngủ ngon thật ấm áp và dễ thương nhé ❤️', 'daily'),
('Thử dành cho đối phương những cử chỉ ngọt ngào như khen ngợi phong cách ăn mặc hoặc mùi nước hoa hôm nay để tình cảm thêm bền chặt 🌷', 'daily'),
('Hãy dành cho đối phương những cử chỉ ngọt ngào như nắm tay thật chặt khi cùng nhau đi bộ dưới phố nhé nửa kia yêu dấu 🥰', 'daily'),
('Thử dành cho tình yêu của bạn những cử chỉ ngọt ngào như nhắn tin hỏi thăm xem có mệt không nhé người thương ✨', 'daily'),
('Hôm nay là ngày tuyệt vời để gọi điện thoại chỉ để nghe giọng nói quen thuộc 🍿', 'daily'),
('Hôm nay bạn hãy cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé 💕', 'daily'),
('Thử dành cho người thương những cử chỉ ngọt ngào như kiên nhẫn lắng nghe những tâm sự nhỏ to sau ngày làm việc nha người ấy ơi 😘', 'daily'),
('Thử dành cho người thương những cử chỉ ngọt ngào như rủ đi uống trà sữa hoặc ăn món ăn vặt yêu thích để ngày hôm nay thêm ngọt ngào 🤗', 'daily'),
('Hãy dành thời gian dành cho tình yêu của bạn những cử chỉ ngọt ngào như dành cho nhau 10 phút nói chuyện hoàn toàn không bấm điện thoại nhé 🥰', 'daily'),
('Hãy dành thời gian dành cho người thương những cử chỉ ngọt ngào như nắm tay thật chặt khi cùng nhau đi bộ dưới phố để ngày hôm nay thêm ngọt ngào 🥳', 'daily'),
('Đừng quên dành cho người thương những cử chỉ ngọt ngào như dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc nha tình yêu 💋', 'daily'),
('Hôm nay bạn hãy cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé ☀️', 'daily'),
('Hãy dành cho người ấy những cử chỉ ngọt ngào như gửi một lời chúc ngủ ngon thật ấm áp và dễ thương nha 🍿', 'daily'),
('Hôm nay là ngày tuyệt vời để nhắn tin hỏi thăm xem có mệt không nhé 💋', 'daily'),
('Hôm nay hãy cùng nhau chụp một tấm ảnh tự sướng mới nhất nhé 🤗', 'daily'),
('Đừng quên dành cho nửa kia những cử chỉ ngọt ngào như dành một lời khen ngợi chân thành về nụ cười hoặc mái tóc nha 🍀', 'daily'),
('Hãy dành thời gian dành cho tình yêu của bạn những cử chỉ ngọt ngào như chia sẻ một câu chuyện vui vẻ bạn gặp hôm nay nha người ấy ơi 🥰', 'daily'),
('Hãy dành cho tình yêu của bạn những cử chỉ ngọt ngào như lên kế hoạch cho một buổi hẹn hò lãng mạn cuối tuần này để ngày hôm nay thêm ngọt ngào 🍀', 'daily'),
('Hãy luôn dành cho tình yêu của bạn những cử chỉ ngọt ngào như nhắn tin hỏi thăm xem có mệt không nhé nửa kia yêu dấu 🥰', 'daily'),
('Thử dành cho đối phương những cử chỉ ngọt ngào như viết một mẩu giấy nhớ ngọt ngào gửi kèm nhé 🍿', 'daily'),
('Hôm nay bạn hãy gửi một lời chúc ngủ ngon thật ấm áp và dễ thương 😍', 'daily'),
('Hôm nay bạn hãy nhắn tin hỏi thăm xem có mệt không nhé ☀️', 'daily'),
('Hôm nay là ngày tuyệt vời để hỏi xem hôm nay người ấy có chuyện gì vui không nhé 🍀', 'daily'),
('Hãy dành thời gian dành cho tình yêu của bạn những cử chỉ ngọt ngào như nắm tay thật chặt khi cùng nhau đi bộ dưới phố để ngày hôm nay thêm ngọt ngào 🍀', 'daily'),
('Hãy dành thời gian dành cho tình yêu của bạn những cử chỉ ngọt ngào như rủ đi uống trà sữa hoặc ăn món ăn vặt yêu thích nhé 🧸', 'daily'),
('Hãy luôn dành cho nửa kia những cử chỉ ngọt ngào như rủ đi uống trà sữa hoặc ăn món ăn vặt yêu thích nha 😍', 'daily'),
('Đừng quên dành cho người ấy những cử chỉ ngọt ngào như gửi một bài hát ngọt ngào mà bạn vô tình nghe thấy nha người thương 🥤', 'daily');

INSERT INTO public.daily_wishes (content, type, special_month, special_day, special_event) VALUES
('Chúc mừng Ngày Lễ Tình Nhân Valentine! 💕 Cảm ơn em vì đã là nửa kia hoàn hảo nhất của anh. Anh yêu em mãi mãi!', 'special', 2, 14, 'valentine'),
('Giáng Sinh ấm áp bên em! 🎄 Chúc tình yêu của chúng mình luôn rực rỡ và ấm áp như những ngọn nến đêm Noel.', 'special', 12, 25, 'christmas'),
('Chúc mừng Ngày Quốc tế Phụ nữ 8/3! 💐 Gửi tới người con gái anh yêu những lời chúc tốt đẹp nhất, em luôn là bông hoa đẹp nhất trong lòng anh.', 'special', 3, 8, 'womens_day'),
('Chúc mừng Ngày Phụ nữ Việt Nam 20/10! 💕 Chúc em luôn xinh đẹp, hạnh phúc và bình yên bên anh nhé!', 'special', 10, 20, 'vietnamese_womens_day'),
('Happy New Year! 🎆 Chúc mừng năm mới tình yêu của anh! Mong rằng chúng ta sẽ cùng nhau đi qua thêm nhiều năm tháng tuyệt vời nữa.', 'special', 1, 1, 'new_year');
